name: CI_update_remote

on:
  # normal conditions
  push:
  pull_request:

  # on demand, from Actions tab
  workflow_dispatch:

  # on schedule (using cron syntax)
  schedule:
    - cron: "0 0 1 * *" #< first day of every month at 00:00 UTC

jobs:
  update:
    # This job would annoy people who fork the template, or if plugintemplate ever becomes a "template repository"
    #   if someone _wants_ this, change the name to match their own fork or project
    if: ${{ github.repository_name == 'notepad-plus-plus/plugintemplate' }} || ${{ github.repository_name == 'pryrt/plugintemplate' }}

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release]
        build_platform: [x64]

    steps:
    - name: Checkout plugintemplate repo
      uses: actions/checkout@v4

    - name: Checkout N++ repo
      uses: actions/checkout@v4
      with:
        repository: notepad-plus-plus/notepad-plus-plus
        path: npp_repo

    - name: Diff the hashes
      id: diff_step
      run: |
        # start assuming no differences
        $anyDifference = $false
        #
        # scintilla hashes: for plugintemplate (hps) and npp (hns)
        #
        $fps = "src\Scintilla.h"
        $fns = "npp_repo\scintilla\include\Scintilla.h"
        $hps = Get-FileHash $fps -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        $hns = Get-FileHash $fns -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        if ($hps -ne $hns) {
            $anyDifference = $true
            Copy-Item -path $fns -destination $fps -force
        }
        #
        # Notepad_plus_msgs.h hashes: for plugintemplate (hpn) and npp (hnn)
        $fpn = "src\Notepad_plus_msgs.h"
        $fnn = "npp_repo\PowerEditor\src\MISC\PluginsManager\Notepad_plus_msgs.h"
        $hpn = Get-FileHash $fpn -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        $hnn = Get-FileHash $fnn -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        if ($hpn -ne $hnn) {
            $anyDifference = $true
            Copy-Item -path $fnn -destination $fpn -force
        }
        #
        # use  GITHUB_OUTPUT to propagate a value that will be able to control the conditional on a future step
        if ($anyDifference) {
            "ANY_DIFFERENCE=True" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        }
        #
        # Store the date:
        $dateNow = (Get-Date).ToString("yyyy_MMMM_dd")
        echo "CHANGE DATE will be $dateNow"
        "CHANGE_DATE=$dateNow" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        #
        # get rid of the extra hierarchy now that the hash
        Remove-Item .\npp_repo -Force -Recurse -ErrorAction SilentlyContinue
        #
        git status

    - name: If ANY_DIFFERENCE then add MSBuild to PATH
      if: ${{steps.diff_step.outputs.ANY_DIFFERENCE}}
      uses: microsoft/setup-msbuild@v1

    - name: If ANY_DIFFERENCE then run MSBuild of plugin dll
      if: ${{steps.diff_step.outputs.ANY_DIFFERENCE}}
      working-directory: vs.proj\
      run: msbuild NppPluginTemplate.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Commit any updates to the repo
      if: ${{steps.diff_step.outputs.ANY_DIFFERENCE}}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updating plugintemplate based on most recent N++ repo (${{ steps.diff_step.outputs.CHANGE_DATE }})

    # sometime in the future, need to try to create a tag and then release it
    #   maybe based on https://graphite.dev/guides/how-to-automate-tagging-and-release-workflows-in-github and softprops/action-gh-release
    ## - name: Release
    ##   if: ${{steps.diff_step.outputs.ANY_DIFFERENCE}}
    ##   uses: softprops/action-gh-release@v2
    ##   with:
    ##     body: Updating plugintemplate based on most recent N++ repo (${{ steps.diff_step.outputs.CHANGE_DATE }})
    ##     name: v${{ steps.diff_step.outputs.CHANGE_DATE }}
